### PR TITLE
Ogre 2.1 New Branch

### PR DESCRIPTION
**Pull request by DotWolff**

### CODE REVIEW

**Comment by al2950** [comment]
Hi, is there any chance this pull request be accepted please!?

**Comment by scrawl** [comment]
Sorry, I totally forgot.

Are all those HLMS files really necessary? Can we reduce to just the files necessary to run MyGUI?

**Comment by al2950** [comment]
I guess I could write a cmake script to grab the HLMS files at compile time. Technically we only need the HLMS unlit, but PBS is the default default material!

What would you like to do?

**Comment by scrawl** [comment]
So the PBS files can be removed? Let's do that then.

**Comment by al2950** [comment]
Slight issue is that the majority of the changes are mine, but the PR is from DotWolff. If you would be happy, you could accept the pull request and then I could sync and remove the HLMS files and create a pull request directly from my fork.

I think it would be best to refer the the HLMS files directly from the Ogre repo, as if they come out of sync with the C++ part they may not work properly.

**Comment by aymarfisherman** [comment]
I believe the HLMS files should be completely removed from MyGUI and just throw an exception saying the Unlit Hlms was not registered when firing MyGUI (if I'm not mistaken we did this in the first iteration). 

Although it would make setting up a little more complicated (just a little, since the Unlit Hlms comes with Ogre and people would only have to register the Hlms), it would avoid unnecessary files in the MyGUI rep and it would avoid having duplicate OR conflicting HLMS Unlit files when those evolve in the Ogre rep. 

Unless you are talking about the examples...

**Comment by al2950** [comment]
@aymarfisherman

Thank you!

**Pull request merged**
