### PR TITLE
Use unique_ptr in Delegate

### PR DESCRIPTION
**Pull request by Assumeru**
Replaces manual memory management and its corresponding destructors with `std::unique_ptr`. `MultiDelegate::mListDelegates` can no longer contain `nullptr`s, removing the need for `mutable`.

I noticed that `MultiDelegate::clear(IDelegateUnlink*)` and `MultiDelegate::operator-=(IDelegate*)` are effectively the same function with the latter taking ownership of its argument pointer. Ideally it'd take an `std::unique_ptr<IDelegate>&&` argument instead (and the same goes for `Delegate`'s assignment operator and `MultiDelegate`'s `+=`) but that'd probably involve making `newDelegate` return `std::unique_ptr` as well, which would be a larger change.

### CODE REVIEW

**Comment by Altren** [comment]
Nice. I guess the next step would be changing MyGUI::newDelegate, so that it return unique_ptr and new/delete is no longer called in the delegates related code

**Comment by Altren** [comment]
By the way, there is one downside in this change: now we instantiate std::unique_ptr for each delegate type and in typical project there are plenty of them. I'll do some investigation in a couple of days to make sure that this is not a significant issue.

**Comment by Assumeru** [comment]
Ideally a compiler would produce the exact same output as before, but that's probably too optimistic. A minimal godbolt version shows a reduction in the number of lines of assembly output by GCC at -O1, but that also doesn't mean much.
https://godbolt.org/z/acTPGKh1r https://godbolt.org/z/vxP6Wz197

Depending on how common `mListDelegates` manipulation is, it might be worthwhile to switch from `std::list` to `std::vector`.

**Comment by Altren** [comment]
The scenario I'm talking about is when you have multiple different delegates. Try to create 5 different delegates (with different signature) in your test.

**Comment by Altren** [comment]
That's great. This mean that unique_ptr is either more simple that the deleted lines or compiler eliminates it well enough. Anyway this proves that I was wrong about downside of your change, which is good

**Comment by Altren** [comment]
It seems, that there is regression in this change. LayoutEditor crashes at start. Reverting this changes fixes the issue

**Pull request merged**
