### PR TITLE
Add missing MYGUI_EXPORT on ControllerRepeatClick

### LINKED ISSUE #213: MyGUI 3.4.1 link error: "undefined reference to `typeinfo for MyGUI::ControllerRepeatClick'" (dynamic linking only)
This happens with OpenMW when linking against 3.4.1 dynamically https://gitlab.com/OpenMW/openmw/-/issues/5897

Static linking works, 3.4.0 works both statically and dynamically

Any idea what could have caused this?

### PR DESCRIPTION
**Pull request by glebm**
Fixes #213

### CODE REVIEW

**Comment by Altren** [comment]
Thank you. I'm curious how it worked before.

**Comment by glebm** [comment]
Previously, OpenMW mostly used the distribution package (e.g. Debian). Perhaps the distribution package compiled with different flags. I hit this issue using when using MyGUI that I compiled from source.

**Comment by psi29a** [comment]
I think this might need a bug-fix release so that downstream can create packages.

**Comment by glebm** [comment]
Perhaps whatever's causing #214 can be fixed and go into the same bugfix release

**Pull request merged**
