### PR TITLE
fix mac compile errors

### PR DESCRIPTION
**Pull request by xzwang2005**
changed nullptr to NULL to avoid type convertion error on Mac based on scrawl's feedback

### CODE REVIEW

**Comment by Altren** [comment]
I understand, that NULL is widely used, but is it defined or explicitly included from any place?

**Comment by scrawl** [comment]
```#include <cstddef>``` gets you the NULL define. Looks like something is pulling in that header implicitely. If it matters, we could add explicit includes.

https://stackoverflow.com/questions/924664/why-is-null-undeclared

**Comment by Altren** [comment]
I understand that I'm a bit late, but why not fix this in shared pointer. Also it is possible to define it out when code is compiled with c++11 support.
Current "fix" doesn't prevent from this problem appearing again.

**Comment by scrawl** [comment]
> why not fix this in shared pointer

That is what we tried. :( The fix worked for comparison ops, but didn't work for assignment, and I don't know why. 

Unfortunately I can't reproduce the error on my end, even when compiling with -std=c++0x, so I'm not sure how to proceed.

See discussion on https://github.com/MyGUI/mygui/commit/c86490dbd2b5806838f2e563dbec30fbc600e9f1#commitcomment-11780736. I'm all ears if you have an idea.

**Comment by Altren** [comment]
Current check for nullptr define is completely wrong on any compiler other than MSVC.
@xzwang2005 Could you check if everything compiles with next definition in MyGUI_Prerequest.h:

    #ifndef MYGUI_DONT_REPLACE_NULLPTR
    #	if __cplusplus < 201103L && !_NATIVE_NULLPTR_SUPPORTED
    #		define nullptr 0
    #	endif
    #endif

**Comment by scrawl** [comment]
Good find. That piece of code looked suspicious but I didn't make the connection for some reason.

**Comment by scrawl** [comment]
Could we make that 
<pre>
#   if __cplusplus < 201103L && !defined(_NATIVE_NULLPTR_SUPPORTED)
</pre>
instead, as I don't seem to have _NATIVE_NULLPTR_SUPPORTED defined here. With -Wundef, gcc would emit a warning when using the value of an undefined macro, which is a nice and useful warning to have.

**Comment by Altren** [comment]
Right, not defined should work as well.

**Comment by xzwang2005** [comment]
do you want to keep the "if MYGUI_COMPILER == MYGUI_COMPILER_MSVC" part ? 
or replace the whole thing within "#ifndef MYGUI_DONT_REPLACE_NULLPTR" ?

**Comment by Altren** [comment]
Replace whole thing.

**Comment by xzwang2005** [comment]
sorry guys, not working, it gives the same error when assign nullptr to a shared_ptr<>, e.g.,
/mygui/Tools/SkinEditor/SkinExportSerializer.cpp:345:12: No viable conversion from 'std::__1::nullptr_t' to 'DataPtr' (aka 'shared_ptr<tools::Data>')

**Comment by Altren** [comment]
I pushed proper fix to master.

**Comment by scrawl** [comment]
Looks good. I reverted the NULL change.

**Pull request merged**
