### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by psi29a**

### CODE REVIEW

**Comment by Altren** [comment]
Commit such changes directly into master next time :)

**Comment by psi29a** [comment]
Didn't I do that? I don't have access to MyGUI... I think you kicked me out and I don't have permissions.  ;)

**Comment by psi29a** [comment]
> You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork psi29a/mygui, so you can send a pull request.

**Comment by Altren** [comment]
Odd. For some reason MyGUI/developers group (you are in this group) had no access to the repository. I fixed that.

**Comment by psi29a** [comment]
I've also packaged 3.4.0 for Debian (and Ubuntu); awaiting a friendly FTP uploader to get it into Debian. :D
https://salsa.debian.org/psi29a-guest/MyGUI

**Pull request merged**
