### PR TITLE
correct vertex color order for ogre 13

### LINKED ISSUE #230: widget colors are inverted with Ogre 1.13 and DX9
According to [https://github.com/OGRECave/ogre/blob/master/Docs/13-Notes.md#breaking-non-api-changes](https://github.com/OGRECave/ogre/blob/master/Docs/13-Notes.md#breaking-non-api-changes):

> VET_COLOUR* is now an alias for VET_UBYTE4_NORM. On most RenderSystems VET_COLOUR would be already mapped to VET_UBYTE4_NORM anyway. A notable exception is D3D9, where this changes the channel order from BGRA to RGBA. If you are using custom vertex shaders, you must update them accordingly. 

I guess this is why colors are wrong in my app: B and R seems to be inverted.

### PR DESCRIPTION
**Pull request by paroj**
fixes #230

### CODE REVIEW

**Comment by sercero** [comment]
Thanks!

**Comment by Altren** [comment]
Could you explain the reason why this helps? All I can see is two swapped if's. Does Ogre have identical enum values?

**Comment by paroj** [comment]
yes, as cited in the bug report:
> VET_COLOUR* is now an alias for VET_UBYTE4_NORM. On most RenderSystems VET_COLOUR would be already mapped to VET_UBYTE4_NORM anyway. A notable exception is D3D9, where this changes the channel order from BGRA to RGBA. If you are using custom vertex shaders, you must update them accordingly.

**Comment by Altren** [comment]
Thank you

**Pull request merged**
