### PR TITLE
Fix install path of pkg-config file, libs

### PR DESCRIPTION
**Pull request by h3xx**
Use GNUInstallDirs to determine where libraries should be installed, rather than just assume they're to be installed in {PREFIX}/lib

[More info on GNUInstallDirs can be found here](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html)

### CODE REVIEW

**Comment by Altren** [comment]
Which platforms you tested with this changes? Does this affect windows builds?

**Comment by h3xx** [comment]
This potentially affects every build that calls `make install` and has a directory called `'lib'` in its installed directory list.

I've tested thoroughly a build on Linux x86_64 with the following cmake(1) options:

    cmake \
        -DMYGUI_BUILD_{DEMOS,DOCS}=OFF \
        -DCMAKE_C_FLAGS_RELEASE='-O3 -DNDEBUG -std=c++0x' \
        -DCMAKE_CXX_FLAGS='-std=c++0x' \
        /tmp/git/mygui

Before the patch was applied, the `make install` command installed the pkg-config scripts in `$DESTDIR/usr/lib/pkgconfig`, instead of where they were supposed to be installed on a 64-bit system, `/usr/lib64/pkconfig`.

I've been unable to test using the Windows build instructions due to the fact I (willingly) do not have access to a Windows machine.

**Comment by Altren** [comment]
Please fix typo in the MyGUIConfigTargets.cmake  line 65, that I mentioned above, then I'll merge the pull request

**Comment by h3xx** [comment]
Updated. Also fixed a couple of places I missed.

**Comment by Altren** [comment]
Sorry for not merging this earlier. I missed your last update. And thank you for contribution.

**Pull request merged**
