### PR TITLE
CTRL arrow key behaviour

### PR DESCRIPTION
**Pull request by Assumeru**
This PR implements moving the text cursor between words using CTRL+right arrow and CTRL+left arrow.

### CODE REVIEW

**Comment by Altren** [comment]
I'm not sure if there is a good way to merge this two very similar pieces of code, but you should move to the helper function this check: `text[mCursorPosition] != ' ' && text[mCursorPosition] != '\t'` and use it in all four cases. Also this way you can add more delimeters, f.e. `\n`

**Comment by Assumeru** [comment]
Should I add a new member so people can specify their own delimiters or define it as a virtual function so it can be overridden?

**Comment by Altren** [comment]
Since this is a minor feature and never been requested before it is OK to add a simple private function

**Comment by Altren** [comment]
Thank you

**Pull request merged**
