### PR TITLE
allow disable DynLib code by MYGUI_DONT_USE_DYNLIB macros

### PR DESCRIPTION
**Pull request by andryblack**
Fully disable dynamic code loading option

### CODE REVIEW

**Comment by scrawl** [comment]
I fail to see a value in this patch. If you don't want to load dynamic libraries, then... just don't load any?

**Comment by Altren** [comment]
Could you describe when such option might be needed?

**Comment by andryblack** [comment]
Some platforms, (iOS for example) disallow dynamic code loading. This patch allow build application without dynamic code loading imported functions.

**Comment by scrawl** [comment]
Ok, I'm fine with the idea, but would like to see a few changes before merging:

- A cmake option controlling the define, along with a description when to use it (as you posted above).
- Conditional compiling should be limited to the .cpp file, so there are no issues with mismatching compile flags (i.e. an application including MyGUI_DynLib.h having different compile flags than MyGUI_DynLib.cpp was compiled with).
- If you attempt to load a dynamic library while MyGUI was built without dynamic library support, there should be a warning in the log file or an exception.

**Comment by Altren** [comment]
Fixed.

**Pull request closed without merging**
