### PR TITLE
Ogre2.1

### PR DESCRIPTION
**Pull request by al2950**
lastest ogre 2.1 update fixes

### CODE REVIEW

**Comment by scrawl** [comment]
I can't review this, can we get a +1 from another user that this works?

**Comment by cryham** [comment]
Well, I tried but I'm still not able to build.
And I did several fixes in project after what CMake did, of paths, includes, lib names.
Seems nothing has changed for better, on how freaking hopeless it is to build it from sources.
Just a greeting from linker:
MyGUI.Ogre2Platform.lib(MyGUI_Ogre2VertexBuffer.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static void __cdecl Ogre::NedPoolingImpl::deallocBytes(void *)" (__imp_?deallocBytes@NedPoolingImpl@Ogre@@SAXPAX@Z)
Where the hell is Ned?

**Comment by al2950** [comment]
@cryham That sucks!
I did my tests with a completely fresh build of Ogre and MyGUI. Have to admit I only tested on of the demos though. The fact you are getting ned malloc erros suggests you are using an old cmake cache for Ogre, as the default allocation has changed back from nedmalloc to 'default'. 

The other thing I had to do to build it was to set the OGRE_SOURCE_DIR cmake option manually and of course set MYGUI_RENDERSYSTEM to 8.

**Comment by jserve** [comment]
Compile went fine with
Visual Studio 2015 Community, Version 14.0.25425.01 Update 3
Ogre Revision 10581

**Pull request merged**
