### PR TITLE
OpenGL3.x+ core profile platform

### PR DESCRIPTION
**Pull request by snoutmate**
Platform for OpenGL 3.0+ core profile support. Large part of it is copy of the existing OpenGL platform (including GLEW).

### CODE REVIEW

**Comment by galek** [comment]
what?
Thanks!

**Comment by Altren** [comment]
Look very promising. I need some time to properly test it.
Also I looked through code and see, that it doesn't support demos build on non-windows platforms. Is it hard to implement?

**Comment by snoutmate** [comment]
I can't test it outside windows at the moment, but there shouldn't be any issues. I copied the building configuration from the existing OpenGL platform, and since it uses GLEW, the building requirements should be identical ? 

The only changes interface-wise compared to the existing OpenGL platform is that *Texture class doesn't support luminance formats (since those are not supported in GL3+), and that *VertexBuffer::getBufferID() method returns VAO id instead of VBO id, since VAO is wrapping the state of that VBO, and is what is used for rendering. 

All the new code is basically in *RenderManager.cpp and *VertexBuffer.cpp, the rest of files (DataManager/Platform/RTTexture/Texture) are virtually untouched.

**Comment by snoutmate** [comment]
Noticed RTT wasn't actually working, oops :) Should be fixed now.

**Pull request merged**
